= CloudBees action: Run New Relic to verify deployment

Use this action to provide post-deployment verification using New Relic, an observability tool that provides real-time data on application health, performance, and usage.

== Inputs

[cols="2a,1a,1a,3a",options="header"]
.Input details
|===

| Input name
| Data type
| Required?
| Description

| `controller-url`
| String
| No
| The New Relic controller URL.

| `infra-conditions-url`
| String
| No
| The New Relic infrastructure conditions URL.

| `api-key`
| String
| Yes
| The New Relic API key.

| `duration`
| String
| Yes
| The verification duration, in milliseconds.

| `policies`
| String, representing an array
| Yes
| The New Relic policies.

| `conditions`
| String, representing an array
| Yes
| The New Relic conditions.
|===

== Usage example

In your YAML file, add:

[source,yaml]
----
  jobs:
    verify-with-newrelic:
      steps:
      - name: Verify post-deploy with New Relic
        uses: cloudbees.io/newrelic-verify-deploy@v1
        with:
          api-key: ${{ secrets.NEWRELIC_API_KEY }}
          duration: '10000'
          policies: '["Kubernetes default alert policy"]'
          conditions: '["Pod is not ready","Pod was unable to be scheduled","Container memory usage % is too high"]'
          infra-condition-url: https://my-infra.newrelic.com

----

== License

This code is made available under the 
link:https://opensource.org/license/mit/[MIT license].

== References

* Learn more about link:https://docs.cloudbees.com/docs/cloudbees-saas-platform-actions/latest/[using actions in CloudBees workflows].
* Learn about link:https://docs.cloudbees.com/docs/cloudbees-saas-platform/latest/[the CloudBees platform].
